username: sebas
packages:
  # Base
  - base-devel
  - nodejs
  - python
  - man
  - less
  - unzip
  - fd
  - fzf
  - ripgrep
  - curl
  - jq
  - openssh
  - starship
  # audio
  - pipewire
  - pipewire-pulse
  - pipewire-alsa
  - pipewire-jack
  - wireplumber
  - sof-firmware
  - alsa-ucm-conf
  - pavucontrol
  # utilities
  - wl-clipboard
  - brightnessctl
  - grim
  - slurp
  - satty
  - xdg-desktop-portal
  - xdg-desktop-portal-wlr
  - qt5-wayland
  - qt6-wayland
  - pacman-contrib
  # font
  - ttf-jetbrains-mono
  # sway
  - sway
  - swaync
  - swaybg
  - swaylock
  - swayidle
  - swayimg
  # apps
  - waybar
  - rofi
  - keepassxc
  - docker
  - docker-compose
  - libreoffice
  - firefox
  - thunderbird
  - gimp
  - mpv
  - thunar
