username: sebas
packages:
  # Base
  - base-devel
  - man
  - starship
  - less
  - tealdeer
  - exa
  - bat
  - git-delta
  - fd
  - fzf
  - jq
  - ripgrep
  - wl-clipboard
  - curl
  - openssh
  - nodejs
  - waybar
  - pavucontrol
  - pipewire
  - wireplumber
  - brightnessctl
  - xdg-desktop-portal
  - xdg-desktop-portal-hyprland
  - polkit-kde-agent
  - qt5-wayland
  - qt6-wayland
  - grim
  - slurp
  # font
  - ttf-jetbrains-mono
  # apps
  - keepassxc
  - docker
  - docker-compose
  - libreoffice
  - firefox
  - thunderbird
