- name: Enable Audio (PipeWire)
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
    scope: user
  loop:
    - pipewire.service
    - pipewire-pulse.service
    - wireplumber.service
