- name: Enable PipeWire Services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
    scope: user
  loop:
    - pipewire.service
    - pipewire-pulse.service
    - wireplumber.service

- name: Enable Bluetooth Service
  become: yes
  ansible.builtin.systemd:
    name: bluetooth
    enabled: yes
    state: started
