- name: Aur
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    state: present
    name: 
      - wezterm-git
      - implay
      - neovim-nightly-bin
      - swaync
      - rofi-lbonn-wayland-git

- name: Install Rofi Calculator
  community.general.pacman:
    name: rofi-calc
    state: latest
