- name: Update AUR packages
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    upgrade: yes
    use: yay
    aur_only: yes

- name: Install AUR packages
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    state: present
    name: 
      - kanata
      - wezterm-git

- name: Install Rofi Calculator
  community.general.pacman:
    name: rofi-calc
    state: latest
