- name: Set System Timezone
  become: true
  community.general.timezone:
    name: America/Argentina/Buenos_Aires

- name: Validate target distribution
  ansible.builtin.assert:
    that:
      - target_distribution in ['arch', 'debian']
    fail_msg: "target_distribution must be either 'arch' or 'debian'."

- name: Enable time sync
  become: true
  ansible.builtin.service:
    name: systemd-timesyncd
    state: started
    enabled: true

- name: Avoid installing debug version
  ansible.builtin.lineinfile:
    path: /etc/makepkg.conf
    regexp: "^OPTIONS="
    line: "OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)"
  when: target_distribution == 'arch'

- name: Enable color and parallel downloads in pacman.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: '^#Color', line: 'Color' }
    - { regexp: '^#ParallelDownloads', line: 'ParallelDownloads = 5' }
  when: target_distribution == 'arch'

- name: Enable eyecandy
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    line: "ILoveCandy"
    insertafter: "^\\s*Color$"
    state: present
  when: target_distribution == 'arch'

- name: Update Pacman
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true
  when: target_distribution == 'arch'

- name: Update Ansible Repo
  ansible.builtin.git:
    repo: git@github.com:SebasF1349/ansible.git
    dest: /home/sebas/ansible
    clone: yes
    update: yes
    accept_hostkey: yes
    key_file: /home/sebas/.ssh/id_ed25519
  when: testing is defined and testing == '1'
