- name: Avoid installing debug version
  ansible.builtin.lineinfile:
    path: /etc/makepkg.conf
    regexp: "^OPTIONS="
    line: "OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)"

- name: Update Pacman
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Update Ansible Repo
  git:
    repo: git@github.com:SebasF1349/ansible.git
    dest: /home/sebas/ansible
    clone: yes
    update: yes
    accept_hostkey: yes
    key_file: /home/sebas/.ssh/id_ed25519
  when: testing is defined and testing == '1'

