- name: Install firewall
  become: yes
  community.general.pacman:
    name: ufw
    state: latest

- name: Disable incoming traffic
  become: yes
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming
    
- name: Allow all outgoing traffic (default)
  become: yes
  community.general.ufw:
    policy: allow
    direction: outgoing
    state: enabled

- name: Allow incoming SSH on port 22
  become: yes
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp
    comment: Allow SSH access
    state: enabled

- name: Ensure UFW is enabled and running
  become: yes
  community.general.ufw:
    state: enabled
