- name: Install Flatpak
  community.general.pacman:
    name: flatpak
    state: latest
  register: flatpak
  when: target_distribution == 'arch'

- name: Install Flatpak
  ansible.builtin.apt:
    name: flatpak
    state: latest
    update_cache: true
  register: flatpak
  when: target_distribution == 'debian'

- name: Add flathub remote repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: http://dl.flathub.org/repo/flathub.flatpakrepo
  when: flatpak.changed
    
- name: Install Flatpaks
  community.general.flatpak:
    name:
      - us.zoom.Zoom
      - com.obsproject.Studio
    state: present
  register: installation
