- name: Install Packages with Pacman
  become: true
  community.general.pacman:
    name: "{{ arch_common_packages }}"
    state: latest
    update_cache: yes
  when: target_distribution == 'arch'

- name: Install x11 Packages with Pacman
  become: true
  community.general.pacman:
    name: "{{ arch_x11_packages }}"
    state: latest
    update_cache: yes
  when:
    - target_distribution == 'arch'
    - not use_wayland | bool

- name: Install Wayland Packages with Pacman
  become: true
  community.general.pacman:
    name: "{{ arch_wayland_packages }}"
    state: latest
    update_cache: yes
  when:
    - target_distribution == 'arch'
    - use_wayland | bool

- name: Install Packages with Apt
  become: true
  ansible.builtin.apt:
    name: "{{ debian_common_packages }}"
    state: latest
    update_cache: yes
  when: target_distribution == 'debian'

- name: Install x11 Packages with Apt
  become: true
  ansible.builtin.apt:
    name: "{{ debian_x11_packages }}"
    state: latest
    update_cache: yes
  when:
    - target_distribution == 'debian'
    - not use_wayland | bool

- name: Install Wayland Packages with Apt
  become: true
  ansible.builtin.apt:
    name: "{{ debian_wayland_packages }}"
    state: latest
    update_cache: yes
  when:
    - target_distribution == 'debian'
    - use_wayland | bool

- name: Enable Paccache
  become: yes
  ansible.builtin.systemd:
    name: paccache.timer
    enabled: yes
    state: started
  when: target_distribution == 'arch'
