- name: Install Packages with Pacman
  become: true
  community.general.pacman:
    name: "{{ arch_common_packages }}"
    state: latest
    update_cache: yes
  when: target_distribution == 'arch'

- name: Install x11 Packages with Pacman
  become: true
  community.general.pacman:
    name: "{{ arch_x11_packages }}"
    state: latest
    update_cache: yes
  when:
    - target_distribution == 'arch'
    - not use_wayland | bool

- name: Install Wayland Packages with Pacman
  become: true
  community.general.pacman:
    name: "{{ arch_wayland_packages }}"
    state: latest
    update_cache: yes
  when:
    - target_distribution == 'arch'
    - use_wayland | bool

- name: Install Packages with Apt
  become: true
  ansible.builtin.apt:
    name: "{{ debian_common_packages }}"
    state: latest
    update_cache: yes
  when: target_distribution == 'debian'

- name: Install x11 Packages with Apt
  become: true
  ansible.builtin.apt:
    name: "{{ debian_x11_packages }}"
    state: latest
    update_cache: yes
  when:
    - target_distribution == 'debian'
    - not use_wayland | bool

- name: Install Wayland Packages with Apt
  become: true
  ansible.builtin.apt:
    name: "{{ debian_wayland_packages }}"
    state: latest
    update_cache: yes
  when:
    - target_distribution == 'debian'
    - use_wayland | bool

- name: Enable Paccache
  become: yes
  ansible.builtin.systemd:
    name: paccache.timer
    enabled: yes
    state: started
  when: target_distribution == 'arch'

- name: Locate fdfind Executable
  ansible.builtin.command: which fdfind
  register: fdfind_path
  changed_when: false
  when: target_distribution == 'debian'

- name: Ensure ~/.local/bin Exists
  ansible.builtin.file:
    path: ~/.local/bin
    state: directory
    mode: '0755'
  when: target_distribution == 'debian'

- name: Link fdfind to fd
  ansible.builtin.file:
    src: "{{ fdfind_path.stdout }}"
    dest: ~/.local/bin/fd
    state: link
    force: yes
  when: target_distribution == 'debian'
