- name: Install Packages with Pacman
  community.general.pacman:
    name: "{{ packages }}"
    state: latest

- name: Remove Pacman Packages
  community.general.pacman:
    name:
      - wofi
      - rofi
    state: absent
