- name: Install Reflector
  community.general.pacman:
    name: reflector
    state: latest

- name: Add mirror countries
  ansible.builtin.lineinfile:
    path: /etc/xdg/reflector/reflector.conf
    regexp: "--country"
    line: "--country Brazil, Chile, United States"

- name: Enable reflector timer
  ansible.builtin.systemd_service:
    name: reflector.timer
    enabled: true

- name: Start reflector timer
  ansible.builtin.systemd_service:
    name: reflector.timer
    state: started
