- name: Install Rustup (arch)
  community.general.pacman:
    name: rustup
    state: latest
  register: pacman
  when: target_distribution == 'arch'

- name: Install Rustup (debian)
  become: true
  ansible.builtin.apt:
    name: rustup
    state: latest
    update_cache: yes
  when: target_distribution == 'debian'

- name: Install Rust
  ansible.builtin.shell:
    cmd: rustup default stable
  register: rust_install
  until: rust_install.rc == 0
  retries: 5
  delay: 10
