- name: Install Wezterm
  become: yes
  block:
    - name: Add Wezterm APT Repository
      ansible.builtin.deb822_repository:
        name: wezterm
        types: deb
        uris: https://apt.fury.io/wez/
        suites: "*"
        components: ["*"]
        signed_by: https://apt.fury.io/wez/gpg.key
        state: present
        enabled: yes

    - name: Install Wezterm
      ansible.builtin.apt:
        name: wezterm
        state: present
        update_cache: yes
