- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel
    shell: /bin/bash

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: ALL'
    create: yes
    mode: 0440
    validate: 'visudo -cf %s'

- name: Create ansible directory if it doesn't exists
  become: yes
  become_user: aur_builder
  ansible.builtin.file:
    path: /home/aur_builder/.ansible
    state: directory

- name: Install yay using makepkg if it isn't installed already
  become: yes
  become_user: aur_builder
  vars:
    ansible_env: "/home/aur_builder"
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present
